kevin-lee/extras

build.sbt

Issue #24 - Add `extras-scala-io`

Issue #24 - Add extras-scala-io

---

build.sbt
project/plugins.sbt

Upgraded: sbt-devoops `2.6.0` => `2.10.0`

Upgraded: sbt-devoops 2.6.0 => 2.10.0

---

extras-scala-io/src/main/scala-2/extras/scala/io/syntax/ColorSyntax.scala
extras-scala-io/src/main/scala-2/extras/scala/io/syntax/package.scala
extras-scala-io/src/main/scala-3/extras/scala/io/syntax/ColorSyntax.scala
extras-scala-io/src/main/scala-3/extras/scala/io/syntax/package.scala
extras-scala-io/src/test/scala-2/extras/scala/io/syntax/ColorSyntaxSpec.scala
extras-scala-io/src/test/scala-3/extras/scala/io/syntax/ColorSyntaxSpec.scala
extras-scala-io/src/test/scala/extras/scala/io/ColorGens.scala
extras-scala-io/src/test/scala/extras/scala/io/ColorTestUtils.scala

Close #27 - `ColorSyntax` for typed `AnsiColor` (i.e. `Color`)

Close #27 - ColorSyntax for typed AnsiColor (i.e. Color)

---

build.sbt
extras-cats/src/test/scala-3/extras/cats/syntax/AllSyntaxSpec.scala
extras-cats/src/test/scala-3/extras/cats/syntax/EitherSyntaxSpec.scala
extras-cats/src/test/scala-3/extras/cats/testing/ExecutionContextProvider.scala
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/ConcurrentSupport.scala
extras-concurrent-testing/src/test/scala/extras/concurrent/testing/ConcurrentSupportSpec.scala

Close #36 - Redesign `extras-concurrent-testing` APIs

Close #36 - Redesign extras-concurrent-testing APIs

---

extras-cats/src/test/scala-3/extras/cats/testing/ExecutionContextProvider.scala
extras-cats/src/test/scala-3/extras/cats/testing/IoAppUtils.scala
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/ConcurrentSupport.scala
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/syntax/all.scala
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/syntax/future.scala
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/types.scala
extras-concurrent-testing/src/test/scala/extras/concurrent/testing/ConcurrentSupportSpec.scala
extras-concurrent-testing/src/test/scala/extras/concurrent/testing/syntax/FutureSyntaxSpec.scala
extras-concurrent-testing/src/test/scala/extras/concurrent/testing/syntax/allSpec.scala
extras-concurrent-testing/src/test/scala/extras/concurrent/testing/syntax/futureSpec.scala

Close #41 - Add syntax for testing `Future`

Close #41 - Add syntax for testing Future

---

build.sbt
docs/extras-cats/either.md
docs/extras-cats/get.md
docs/extras-concurrent/get.md
docs/extras-scala-io/_category_.json
docs/extras-scala-io/get.md
website/docusaurus.config.js
website/package-lock.json
website/package.json

Updated: Docs with more about `EitherT` support syntax

Updated: Docs with more about EitherT support syntax

---

website/package-lock.json
website/package.json

Upgraded: `2.0.0-beta.6` => `2.0.0-beta.9`

Upgraded: 2.0.0-beta.6 => 2.0.0-beta.9

---

docs/extras-cats/eithert.md
docs/extras-cats/option.md
docs/extras-cats/optiont.md

Changed: filenames
* `either.md` => `eithert.md`
* `option.md` => `optiont.md`

Changed: filenames

---

docs/intro.md

Updated: Scala versions

---

docs/extras-cats/optiont.md

Updated: The OptionT page

---

website/docusaurus.config.js
website/src/pages/index.js

Updated: The doc site with the poster image infoUpdated: The doc site with the poster image info

Updated: The doc site with the poster image info

---

.github/dependabot.yml

Added: `dependabot.yml` for GitHub Actions

Added: `dependabot.yml` for GitHub Actions

---

.github/pr-labeler.yml
.github/workflows/build.yml
.github/workflows/pr-labeler.yml
.github/workflows/release.yml
.github/workflows/sbt-build-all-with-scala-version.sh
.github/workflows/sbt-build-all.sh

Update: GitHub Actions to make it work with different `crossScalaVersions` setup

Update: GitHub Actions to make it work with different `crossScalaVersions` setup

---

.scalafmt.conf

Update: .scalafmt.conf

---

build.sbt
extras-hedgehog-cats-effect3/src/main/scala/extras/hedgehog/cats/effect/CatsEffectRunner.scala
extras-hedgehog-cats-effect3/src/main/scala/extras/tools.scala
extras-hedgehog-cats-effect3/src/test/scala/extras/hedgehog/cats/effect/CatsEffectRunnerSpec.scala

Close #58 - Add `extras-hedgehog-cats-effect3` to provide `cats-effect3` test kit for `hedgehog`

Close #58 - Add `extras-hedgehog-cats-effect3` to provide `cats-effect3` test kit for `hedgehog`

---

build.sbt
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/types.scala
extras-core/src/main/scala/extras/tools.scala

Close #62 - Add core project to keep all common stuff

Close #62 - Add core project to keep all common stuff

---

changelogs/0.3.0.md

* Add `extras-hedgehog-cats-effect3` to provide `cats-effect3` test kit for `hedgehog` (#58)
* Add core project to keep all common stuff (#62)

extras v0.3.0

---

.github/pr-labeler.yml
.github/workflows/pr-labeler.yml

Fix PR Labeler config

---

build.sbt
project/plugins.sbt

Close #67 - Publish to s01.oss.sonatype.org (the new Maven central)

Close #67 - Publish to s01.oss.sonatype.org (the new Maven central)

---

project/build.properties

Upgrade: sbt `1.5.5` => `1.5.7`

Upgrade: sbt 1.5.5 => 1.5.7

---

build.sbt
docs/extras-cats/getting-started.md
docs/extras-concurrent/_category_.json
docs/extras-concurrent/getting-started.md
docs/extras-hedgehog-cats-effect3/_category_.json
docs/extras-hedgehog-cats-effect3/getting-started.md
docs/extras-hedgehog-cats-effect3/test-with-io.md
docs/extras-scala-io/_category_.json
docs/extras-scala-io/getting-started.md
docs/intro.md

Update: The docs with `extras-hedgehog-cats-effect3`

Update: The docs with extras-hedgehog-cats-effect3

---

project/build.properties

Upgrade: sbt `1.5.7` => `1.5.8`

Upgrade: sbt 1.5.7 => 1.5.8

---

project/plugins.sbt

Upgrade: sbt-docusaur `0.8.0` => `0.8.1`

Upgrade: sbt-docusaur 0.8.0 => 0.8.1

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/sbt-build-all-with-scala-version.sh
.github/workflows/sbt-build-all.sh
project/plugins.sbt

Close #83 - Set up Codecov in GitHub Actions

Close #83 - Set up Codecov in GitHub Actions

---

.github/pr-labeler.yml

Update: PR labeler

---

.github/workflows/checks.yml
.scalafix-scala2.conf
.scalafix-scala3.conf
build.sbt
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/ConcurrentSupport.scala
extras-concurrent-testing/src/test/scala/extras/concurrent/testing/ConcurrentSupportSpec.scala
extras-hedgehog-cats-effect3/src/main/scala/extras/hedgehog/cats/effect/CatsEffectRunner.scala
extras-scala-io/src/main/scala-2.11_2.12/extras/scala/io/CanClose.scala
extras-scala-io/src/main/scala-2.13/extras/scala/io/CanClose.scala
extras-scala-io/src/test/scala-2.11_2.12/extras/scala/io/CanCloseSpec.scala
extras-scala-io/src/test/scala-2.13/extras/scala/io/CanCloseSpec.scala
extras-scala-io/src/test/scala-3/extras/scala/io/CanCloseSpec.scala
project/plugins.sbt

Close #92 - Add Scalafix check

Close #92 - Add Scalafix check

---

.github/workflows/checks.yml
extras-cats/src/main/scala-3/extras/cats/syntax/EitherSyntax.scala
extras-cats/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala
extras-cats/src/test/scala-3/extras/cats/syntax/OptionSyntaxSpec.scala
extras-concurrent-testing/src/main/scala/extras/concurrent/testing/ConcurrentSupport.scala
extras-scala-io/src/main/scala-3/extras/scala/io/CanClose.scala
extras-scala-io/src/test/scala-2.11_2.12/extras/scala/io/CanCloseSpec.scala
extras-scala-io/src/test/scala-2.13/extras/scala/io/CanCloseSpec.scala
extras-scala-io/src/test/scala-3/extras/scala/io/CanCloseSpec.scala
extras-scala-io/src/test/scala-3/extras/scala/io/ColorSpec.scala
project/plugins.sbt

Add `+scalafmtCheckAll` to GitHub Actions

Add +scalafmtCheckAll to GitHub Actions

---

build.sbt
modules/extras-refinement/shared/src/main/scala/extras/refinement/syntax/refinement.scala
modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/refinementSpec.scala
modules/extras-reflects/shared/src/main/scala/extras/reflects/syntax/reflects.scala
modules/extras-reflects/shared/src/test/scala/extras/reflects/syntax/reflectsSpec.scala

Close #101 - Add syntax to support `newtype` and `refined`

Close #101 - Add syntax to support newtype and refined

---

README.md
build.sbt
docs/extras-refinement/_category_.json
docs/extras-refinement/getting-started.md
docs/extras-refinement/syntax.md
docs/extras-reflects/_category_.json
docs/extras-reflects/getting-started.md
docs/intro.md

Update docs with `0.6.0` - `extras-reflects` and `extras-refinement`

Update docs with 0.6.0 - extras-reflects and extras-refinement

---

project/plugins.sbt

Upgrade sbt-docusaur `0.8.1` => `0.9.0`

Upgrade sbt-docusaur 0.8.1 => 0.9.0

---

build.sbt

Close #110 - `extras-refinement`: Downgrade `refined` to `0.9.27`

Close #110 - `extras-refinement`: Downgrade `refined` to `0.9.27`

---

codecov.yml

Add: `codecov.yml` - ignore docs project

Add: codecov.yml - ignore docs project

---

.scalafix-scala2.conf
build.sbt

Add `RemoveUnused` to `.scalafix-scala2.conf`

Add RemoveUnused to .scalafix-scala2.conf

---

docs/extras-reflects/syntax.md

Update: doc for `extras.reflects.syntax.reflects`

Update: doc for extras.reflects.syntax.reflects

---

modules/extras-reflects/shared/src/main/scala/extras/reflects/syntax/classes.scala
modules/extras-reflects/shared/src/main/scala/extras/reflects/syntax/tags.scala
modules/extras-reflects/shared/src/test/scala/extras/reflects/syntax/classesSpec.scala

Add more tests

---

docs/extras-reflects/syntax.md

Update: docs with `extras-reflects` `syntax` (extras `v0.10.0`)

Update: docs with extras-reflects syntax (extras v0.10.0)

---

docs/intro.md

Update docs - Add supported version matrix

Update docs - Add supported version matrix

---

modules/extras-reflects/shared/src/main/scala/extras/reflects/syntax/tags.scala
modules/extras-reflects/shared/src/test/scala/extras/reflects/syntax/tagsSpec.scala

Close #125 - [`extras-reflects`] Add `A.nestedTypeName` `syntax`

Close #125 - [`extras-reflects`] Add `A.nestedTypeName` `syntax`

---

website/package-lock.json

Update: dependencies for the doc site

Update: dependencies for the doc site

---

docs/extras-refinement/syntax.md

Update docs - `extras-refinement` `syntax.md`

Update docs - extras-refinement syntax.md

---

docs/extras-refinement/syntax.md

Update docs - `extras-refinement` `syntax.md` - more info

Update docs - extras-refinement syntax.md - more info

---

modules/extras-scala-io/shared/src/main/scala/extras/scala/io/file/ops.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/opsSpec.scala

Close #131 - [`extras-scala-io`] Add a method to delete all files in a directory and its sub-directories

Close #131 - [extras-scala-io] Add a method to delete all files in a directory and its sub-directories

---

build.sbt
modules/extras-scala-io/shared/src/main/scala-2.11_2.12/extras/scala/io/file/TempFiles.scala
modules/extras-scala-io/shared/src/main/scala-2.13/extras/scala/io/file/TempFiles.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/file/TempFiles.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/FileUtils.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/TempFilesSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/opsSpec.scala

Close #133 - [`extras-scala-io`] Add: Run with temporary directory - `runWithTempDir`

Close #133 - [`extras-scala-io`] Add: Run with temporary directory - `runWithTempDir`

---

changelogs/0.12.0.md

* [`extras-scala-io`] Add a method to delete all files in a directory and its sub-directories (#131)
* [`extras-scala-io`] Add: Run with temporary directory - `runWithTempDir` (#133)

extras v0.12.0

---

modules/extras-scala-io/shared/src/main/scala/extras/scala/io/file/ops.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/opsSpec.scala

Close #138 - Change `getAllFiles` to `listAllFilesRecursively`

Close #138 - Change `getAllFiles` to `listAllFilesRecursively`

---

build.sbt
docs/extras-scala-io/file.md

Update: docs with `extras.scala.io.file`

Update: docs with `extras.scala.io.file`

---

docs/intro.md

Update: docs

---

build.sbt
modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/AllSyntaxSpec.scala
modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/EitherSyntaxSpec.scala
modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/OptionSyntaxSpec.scala
modules/extras-concurrent-testing/shared/src/main/scala/extras/concurrent/testing/ConcurrentSupport.scala
modules/extras-concurrent-testing/shared/src/test/scala/extras/concurrent/testing/ConcurrentSupportSpec.scala
modules/extras-hedgehog-cats-effect3/shared/src/main/scala/extras/hedgehog/cats/effect/CatsEffectRunner.scala
modules/extras-refinement/shared/src/main/scala/extras/refinement/syntax/refinement.scala
modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/refinementSpec.scala
modules/extras-reflects/shared/src/main/scala/extras/reflects/syntax/tags.scala
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/Color.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/Color.scala
modules/extras-scala-io/shared/src/main/scala/extras/scala/io/file/syntax.scala
modules/extras-scala-io/shared/src/test/scala-2.11_2.12/extras/scala/io/CanCloseSpec.scala
modules/extras-scala-io/shared/src/test/scala-2.13/extras/scala/io/CanCloseSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/ColorTestUtils.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/FileUtils.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/TempFilesSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/syntaxSpec.scala
project/plugins.sbt

Upgrade: sbt plugins
- sbt-wartremover 2.4.13 => 3.0.3
- sbt-scalafix 0.9.34 => 0.10.0
- sbt-mdoc 2.2.22 => 2.3.2
- sbt-docusaur 0.9.0 => 0.10.0
- sbt-devoops 2.16.0 => 2.19.0

Upgrade: sbt plugins

---

docs/intro.md

Update: docs - all versions

---

docs/extras-refinement/syntax.md

Update: docs - `extras-refinement/syntax.md` - add `toValue`

Update: docs - extras-refinement/syntax.md - add toValue

---

website/src/css/custom.css

Update: docs - `--ifm-container-width-xl` from `1640px` to `1920px`

Update: docs - `--ifm-container-width-xl` from 1640px to 1920px

---

.scalafmt.conf

Update: `.scalafmt.conf` - 3.4.3 => 3.5.3

Update: .scalafmt.conf - 3.4.3 => 3.5.3

---

.scalafmt.conf

Update: `.scalafmt.conf` - `3.5.3` => `3.5.4` (released 2 days ago)

Update: .scalafmt.conf - 3.5.3 => 3.5.4 (released 2 days ago)

---

modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/syntax/ColorSyntax.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/ColorSyntax.scala
modules/extras-scala-io/shared/src/test/scala-2/extras/scala/io/syntax/ColorSyntaxSpec.scala
modules/extras-scala-io/shared/src/test/scala-3/extras/scala/io/syntax/ColorSyntaxSpec.scala

Close #158 - [`extras-scala-io`] Add more `String.color` to color syntax

Close #158 - [extras-scala-io] Add more String.color to color syntax

---

.scalafmt.conf
project/plugins.sbt

Upgrade: sbt plugins
* `scalafmt` `3.5.4` => `3.5.7`
* `sbt-docusaur` `0.10.0` => `0.11.0`
* `sbt-devoops` `2.19.0` => `2.21.0`
* add `sbt-devoops-starter`

Upgrade: scalafmt 3.5.4 => 3.5.7 / sbt-docusaur 0.10.0 => 0.11.0 / sbt-devoops 2.19.0 => 2.21.0 / add sbt-devoops-starter

---

build.sbt
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/syntax/truecolor/RgbSyntax.scala
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/syntax/truecolor/package.scala
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/truecolor/Rgb.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/truecolor/RgbSyntax.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/truecolor/package.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/truecolor/Rgb.scala
modules/extras-scala-io/shared/src/test/scala-2/extras/scala/io/truecolor/CrossVersionRgbSpec.scala
modules/extras-scala-io/shared/src/test/scala-3/extras/scala/io/truecolor/CrossVersionRgbSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/syntax/truecolor/RgbSyntaxSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/truecolor/Gens.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/truecolor/RgbSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/truecolor/TestTools.scala

Close #162 - [`extras-scala-io`] Add `Rgb` to have true color support

Close #162 - [extras-scala-io] Add Rgb to have true color support

---

modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/syntax/truecolor/RainbowSyntax.scala
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/syntax/truecolor/package.scala
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/truecolor/Rainbow.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/truecolor/RainbowSyntax.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/truecolor/all.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/truecolor/package.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/truecolor/Rainbow.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/syntax/truecolor/RainbowSyntaxSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/truecolor/RainbowSpec.scala

Close #161 - [`extras-scala-io`] Add a way to paint `String` with rainbow 🌈 colors

Close #161 - [`extras-scala-io`] Add a way to paint `String` with rainbow 🌈 colors

---

build.sbt
docs/extras-scala-io/truecolor.md

Update: docs - `truecolor.md` with True Color support

Update: docs - truecolor.md with True Color support

---

.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
docs/extras-cats/extras-cats.md
docs/extras-concurrent/extras-concurrent.md
docs/extras-hedgehog-cats-effect3/extras-hedgehog-cats-effect3.md
docs/extras-refinement/extras-refinement.md
docs/extras-reflects/extras-reflects.md
docs/extras-scala-io/extras-scala-io.md
docs/extras-scala-io/file.md
docs/extras-scala-io/truecolor/_category_.json
docs/extras-scala-io/truecolor/rgb.md
docs/extras-scala-io/truecolor/truecolor.md
docs/intro.md
website/package-lock.json
website/package.json

Upgrade Docusaurus and update doc structure - `2.0.0-beta.9` => `2.0.0-beta.21`

Upgrade Docusaurus and update doc structure - `2.0.0-beta.9` => `2.0.0-beta.21`

---

modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/Color.scala
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/syntax/ColorSyntax.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/Color.scala
modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/ColorSyntax.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/ColorSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/syntax/ColorSyntaxSpec.scala

Close #175 - [`extras-scala-io`] Add `color` and `colored` to `Color`

Close #175 - [extras-scala-io] Add color and colored to Color

---

modules/extras-scala-io/shared/src/test/scala/extras/scala/io/ColorSpec.scala

Add: more tests

---

.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
website/docusaurus.config.js
website/package-lock.json
website/package.json

Close #193 - Replace lunr search with Algolia DocSearch

Close #193 - Replace lunr search with Algolia DocSearch

---

.github/workflows/doc-site-build-only.yml
.github/workflows/doc-site-publish.yml
website/package-lock.json
website/package.json

Close #195 - Upgrade docs site to Docusaurus `2.0.0-rc.1`

Close #195 - Upgrade docs site to Docusaurus `2.0.0-rc.1`

---

project/plugins.sbt

Upgrade: sbt-devoops `2.21.0` => `2.22.0`

Upgrade: sbt-devoops 2.21.0 => 2.22.0

---

build.sbt

Close #199 - Upgrade hedgehog to `0.9.0`

Close #199 - Upgrade hedgehog to 0.9.0

---

docs/extras-scala-io/truecolor/rgb.md

Update: Docs - `rgb.md` - more `syntax` info

Update: Docs - rgb.md - more syntax info

---

.scalafmt.conf

Update: `.scalafmt.conf` - `3.5.7` => `3.5.9`

Update: .scalafmt.conf - 3.5.7 => 3.5.9

---

website/src/css/custom.css

Close #203 - [docs] Add `Fira Code Nerd Font` and `CaskaydiaCove Nerd Font`, and use `Fira Code Nerd Font` for code blocks

Close #203 - [docs] Add `Fira Code Nerd Font` and `CaskaydiaCove Nerd Font`, and use `Fira Code Nerd Font` for code blocks

---

website/src/css/custom.css

Close #203 - [docs] Update CSS to use Nerd Font (now importing css from content-fonts)

Close #203 - [docs] Update CSS to use Nerd Font (now importing css from content-fonts)

---

website/package-lock.json
website/package.json

Close #206 - Upgrade docs site to Docusaurus `2.0.1`

Close #206 - Upgrade docs site to Docusaurus 2.0.1

---

modules/extras-refinement/shared/src/main/scala/extras/refinement/syntax/string.scala
modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/stringSpec.scala

Close #208 - Add `NonEmptyString` concatenation syntax

Close #208 - Add `NonEmptyString` concatenation syntax

---

modules/extras-refinement/shared/src/main/scala/extras/refinement/syntax/all.scala
modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/allSpec.scala
modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/refinementSpec.scala
modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/stringSpec.scala

Close #210 - Add `all` syntax to refinement

Close #210 - Add `all` syntax to refinement

---

docs/extras-refinement/syntax/_category_.json
docs/extras-refinement/syntax/refinement.md
docs/extras-refinement/syntax/string.md
docs/extras-refinement/syntax/syntax.md

Update: Docs with new extras-refinement info (i.e. string syntax)

Update: Docs with new extras-refinement info (i.e. string syntax)

---

codecov.yml
docs/extras-cats/_category_.json
docs/extras-cats/extras-cats.md
docs/extras-concurrent/_category_.json
docs/extras-concurrent/extras-concurrent.md
docs/extras-hedgehog-cats-effect3/_category_.json
docs/extras-hedgehog-cats-effect3/extras-hedgehog-cats-effect3.md
docs/extras-refinement/_category_.json
docs/extras-refinement/extras-refinement.md
docs/extras-reflects/_category_.json
docs/extras-reflects/extras-reflects.md
docs/extras-scala-io/_category_.json
docs/extras-scala-io/extras-scala-io.md
docs/extras-scala-io/truecolor/_category_.json
docs/extras-scala-io/truecolor/truecolor.md
website/package-lock.json
website/package.json

Update: Docs with links in the category page / Upgrade Docusaurus 2.0.1 => 2.1.0

Update: Docs with links in the category page / Upgrade Docusaurus 2.0.1 => 2.1.0

---

build.sbt
modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/CatsEffectRunner.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/CatsEffectRunnerSpec.scala

Close #215 - Rename `extras-hedgehog-cats-effect3` to `extras-hedgehog-ce3`

Close #215 - Rename extras-hedgehog-cats-effect3 to extras-hedgehog-ce3

---

build.sbt
modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/CatsEffectRunner.scala
modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/Ticker.scala
modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/syntax.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/CatsEffectRunnerSyntaxSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSyntaxSpec.scala

Close #216 - [`extras-hedgehog-ce3`] Add support for test returning `IO[Result]`

Close #216 - [`extras-hedgehog-ce3`] Add support for test returning `IO[Result]`

---

project/plugins.sbt

Close #219 - Bump Scala.js
* `sbt-scalajs` to `1.11.0`
* `sbt-scalajs-crossproject` to `1.2.0`

Close #219 - Bump Scala.js

---

modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/CatsEffectRunner.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/CatsEffectRunnerSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/CatsEffectRunnerSyntaxSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSyntaxSpec.scala

Close #221 - [`extras-hedgehog-ce3`] Rename `withIO` to `runIO` in `CatsEffectRunner`

Close #221 - [`extras-hedgehog-ce3`] Rename `withIO` to `runIO` in `CatsEffectRunner`

---

modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/CatsEffectRunner.scala
modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/Ticker.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerWithIOSpec.scala

Close #223 - [`extras-hedgehog-ce3`] Add `withIO` with `implicit ticker =>`

Close #223 - [`extras-hedgehog-ce3`] Add `withIO` with `implicit ticker =>`

---

modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/CatsEffectRunnerSyntaxSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSyntaxSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerWithIoSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerWithIoSyntaxSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/truecolor/RgbSpec.scala

Update: tests

---

build.sbt
docs/extras-hedgehog-ce3/_category_.json
docs/extras-hedgehog-ce3/extras-hedgehog-ce3.md
docs/extras-hedgehog-ce3/with-runner/_category_.json
docs/extras-hedgehog-ce3/with-runner/run-io.md
docs/extras-hedgehog-ce3/with-runner/with-io.md
docs/extras-hedgehog-ce3/with-runner/with-manual-test-context-creation.md
docs/extras-hedgehog-ce3/with-syntax/_category_.json
docs/extras-hedgehog-ce3/with-syntax/run-io.md
docs/extras-hedgehog-ce3/with-syntax/with-io.md
docs/extras-hedgehog-ce3/with-syntax/with-manual-test-context-creation.md
website/src/css/custom.css

Update: docs more about `extras-hedgehog-ce3`

Update: docs more about `extras-hedgehog-ce3`

---

docs/extras-cats/_category_.json
docs/extras-cats/extras-cats.md
docs/extras-concurrent/_category_.json
docs/extras-concurrent/extras-concurrent.md
docs/extras-hedgehog-ce3/extras-hedgehog-ce3.md
docs/extras-refinement/_category_.json
docs/extras-refinement/extras-refinement.md
docs/extras-refinement/syntax/_category_.json
docs/extras-refinement/syntax/syntax.md
docs/extras-reflects/_category_.json
docs/extras-reflects/extras-reflects.md
docs/extras-scala-io/_category_.json
docs/extras-scala-io/extras-scala-io.md
docs/intro.md

Update: docs - `DocCardList`s are now set in the index pages not in the `_category_.json`

Update: docs - `DocCardList`s are now set in the index pages not in the `_category_.json`

---

.github/workflows/dependency-graph.yml

Close #231 - Add `sbt-dependency-submission` GitHub workflow

Close #231 - Add sbt-dependency-submission GitHub workflow

---

modules/extras-core/shared/src/main/scala/extras/core/Render.scala
modules/extras-core/shared/src/test/scala/extras/core/RenderSpec.scala

Close #234 - [`extras-core`] Add `Render[A]` type-class

Close #234 - [`extras-core`] Add `Render[A]` type-class

---

modules/extras-core/shared/src/main/scala/extras/core/syntax/RenderSyntax.scala
modules/extras-core/shared/src/main/scala/extras/core/syntax/package.scala
modules/extras-core/shared/src/test/scala/extras/core/syntax/RenderSyntaxSpec.scala
project/plugins.sbt

Close #238 - [`extras-core`] Add syntax for `Render[A]` type-class

Close #238 - [`extras-core`] Add syntax for `Render[A]` type-class

---

.github/workflows/manual-build.yml
.github/workflows/release.yml

Fix: GitHub Actions release pipeline

Fix: GitHub Actions release pipeline

---

build.sbt
docs/common/intro.md
docs/extras-concurrent/_category_.json
docs/extras-core/_category_.json
docs/extras-core/extras-core.md
docs/extras-core/render.md
docs/extras-hedgehog-ce3/_category_.json
docs/extras-refinement/_category_.json
docs/extras-reflects/_category_.json
docs/extras-scala-io/_category_.json

Update: docs - about `Render[A]`

Update: docs - about Render[A]

---

README.md
build.sbt
docs/common/intro.md
docs/extras-render/_category_.json
docs/extras-render/extras-render.md
docs/extras-render/render.md

Update: docs - with extras-render module info

Update: docs - with extras-render module info

---

modules/extras-render/shared/src/main/scala/extras/render/Render.scala
modules/extras-render/shared/src/test/scala/extras/render/RenderSpec.scala

Close #256 - [`extras-render`] Add `Render.render[A](A => String): Render[A]`

Close #256 - [`extras-render`] Add `Render.render[A](A => String): Render[A]`

---

docs/extras-render/render.md

Update: docs with the change in the new version

Update: docs with the change in the new version

---

docs/extras-render/render.md
docs/extras-render/syntax.md

Update: docs with the new features of `Render`

Update: docs with the new features of Render

---

README.md
docs/common/intro.md

Update: `README.md` and `intro.md`

Update: README.md and intro.md

---

build.sbt
modules/extras-hedgehog-circe/shared/src/main/scala/extras/hedgehog/circe/RoundTripTester.scala
modules/extras-hedgehog-circe/shared/src/test/scala/extras/hedgehog/circe/RoundTripTesterSpec.scala

Close #263 - [`extras-hedgehog-circe`] Add round-trip test support for circe

Close #263 - [extras-hedgehog-circe] Add round-trip test support for circe

---

build.sbt
modules/extras-type-info/shared/src/test/scala-2/extras/typeinfo/syntax/classesSpec.scala
modules/extras-type-info/shared/src/test/scala-3/extras/typeinfo/syntax/classesSpec.scala

Close #273 - [`extras-type-info`] Release `extras-type-info`

Close #273 - [extras-type-info] Release extras-type-info

---

build.sbt

Reformat `build.sbt`

---

build.sbt
modules/extras-render-refined/shared/src/main/scala-2/extras/render/refined/package.scala
modules/extras-render-refined/shared/src/test/scala/extras/render/refined/data/TestData.scala
modules/extras-render-refined/shared/src/test/scala/extras/render/refined/packageSpec.scala
modules/extras-render/shared/src/main/scala/extras/render/Render.scala

Close #277 - [`extras-render-refined`] Add newtype + refined support

Close #277 - [extras-render-refined] Add newtype + refined support

---

website/package-lock.json
website/package.json

Upgrade: Docusaurus 2.1.0 => 2.2.0

Upgrade: Docusaurus 2.1.0 => 2.2.0

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/release.yml
build.sbt
modules/extras-doobie-tools-ce2/shared/src/main/scala/extras/doobie/ce2/DbTools.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala-2/extras/doobie/ce2/data.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala-3/extras/doobie/ce2/data.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/doobie/AutoDeletingFile.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/doobie/RunWithDb.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/doobie/ce2/DbToolsSpec.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/doobie/ce2/Gens.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/runner/RunSync.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/runner/ce2/RunSyncCe2.scala
modules/extras-doobie-tools-ce3/shared/src/main/scala/extras/doobie/ce3/DbTools.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala-2/extras/doobie/ce3/data.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala-3/extras/doobie/ce3/data.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala/extras/doobie/AutoDeletingFile.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala/extras/doobie/RunWithDb.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala/extras/doobie/ce3/DbToolsSpec.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala/extras/doobie/ce3/Gens.scala

Close #283 - Add doobie tools to run SQL query

Close #283 - Add doobie tools to run SQL query

---

.scalafmt.conf
modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/AllSyntaxSpec.scala
modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/EitherSyntaxSpec.scala
modules/extras-concurrent-testing/shared/src/test/scala/extras/concurrent/testing/ConcurrentSupportSpec.scala
modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/CatsEffectRunner.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSyntaxSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerWithIoSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerWithIoSyntaxSpec.scala
modules/extras-hedgehog-circe/shared/src/main/scala-2/extras/hedgehog/circe/RoundTripTester.scala
modules/extras-hedgehog-circe/shared/src/main/scala-3/extras/hedgehog/circe/RoundTripTester.scala
modules/extras-refinement/shared/src/main/scala-2/extras/refinement/syntax/refinement.scala
modules/extras-refinement/shared/src/main/scala-2/extras/refinement/syntax/string.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/syntaxSpec.scala

Update: `.scalafmt.conf` with rewrite rules
- Reformat the code with the new scalafmt config

Update: `.scalafmt.conf` with rewrite rules

---

.scalafix-scala2.conf
.scalafix-scala3.conf
build.sbt
modules/extras-concurrent/shared/src/main/scala/extras/concurrent/ExecutorServiceOps.scala
modules/extras-hedgehog-ce3/shared/src/main/scala/extras/hedgehog/ce3/CatsEffectRunner.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/syntax/truecolor/RainbowSyntaxSpec.scala
modules/extras-scala-io/shared/src/test/scala/extras/scala/io/truecolor/RainbowSpec.scala

Update: `.scalafix-scala2.conf` and `.scalafix-scala3.conf` with more rules including `xuwei-k/scalafix-rules`

Update: `.scalafix-scala2.conf` and `.scalafix-scala3.conf` with more rules including `xuwei-k/scalafix-rules`

---

build.sbt
modules/extras-circe/shared/src/main/scala/extras/circe/codecs/encoder.scala
modules/extras-circe/shared/src/test/scala/extras/circe/codecs/encoderSpec.scala

Close #291 - Add an extension method to circe Encoder to add more fields

Close #291 - Add an extension method to circe Encoder to add more fields

---

.scalafmt.conf
build.sbt

Update: `.scalafmt.conf`

---

build.sbt

Bump effectie from 2.0.0-beta3 => 2.0.0-beta4

Bump effectie from 2.0.0-beta3 => 2.0.0-beta4

---

.scalafix-scala2.conf
build.sbt
modules/extras-fs2-v2-text/shared/src/main/scala-2/extras/fs2/text/syntax.scala
modules/extras-fs2-v2-text/shared/src/main/scala-3/extras/fs2/text/syntax.scala
modules/extras-fs2-v2-text/shared/src/test/scala/extras/fs2/text/syntaxSpec.scala
modules/extras-fs2-v3-text/shared/src/main/scala-2/extras/fs2/text/syntax.scala
modules/extras-fs2-v3-text/shared/src/main/scala-3/extras/fs2/text/syntax.scala
modules/extras-fs2-v3-text/shared/src/test/scala/extras/fs2/text/syntaxSpec.scala

Close #295 - Add fs2 syntax to compile `Stream[F, Byte]` to `F[String]`

Close #295 - Add fs2 syntax to compile `Stream[F, Byte]` to `F[String]`

---

build.sbt
docs/extras-circe/_category_.json
docs/extras-circe/codecs-encoder.md
docs/extras-circe/extras-circe.md
docs/extras-concurrent/_category_.json
docs/extras-fs2/common/_category_.json
docs/extras-fs2/v2/text/_category_.json
docs/extras-fs2/v3/text/_category_.json
docs/extras-hedgehog-ce3/_category_.json
docs/extras-hedgehog-circe/_category_.json
docs/extras-refinement/_category_.json
docs/extras-reflects/_category_.json
docs/extras-scala-io/_category_.json
docs/extras-type-info/_category_.json
modules/extras-circe/shared/src/test/scala/extras/circe/codecs/encoderSpec.scala

Add: docs for `extras-circe`

---

docs/extras-circe/codecs-encoder.md

Update: docs for `extras-circe`

Update: docs for `extras-circe`

---

project/plugins.sbt

Update: plugins.sbt sbt-devoops `2.23.0` => `2.24.0` / sbt-docusaur `0.12.0` => `0.13.0`

Update: plugins.sbt sbt-devoops 2.23.0 => 2.24.0 / sbt-docusaur 0.12.0 => 0.13.0

---

build.sbt
modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/doobie/ce2/Gens.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala/extras/doobie/ce3/Gens.scala

Add hedgehog-extra and update tests for doobie-tools

Add hedgehog-extra and update tests for doobie-tools

---

build.sbt
modules/extras-testing-tools-effectie/shared/src/main/scala-2.12/extras/testing/StubToolsFx.scala
modules/extras-testing-tools-effectie/shared/src/main/scala-2.13_3/extras/testing/StubToolsFx.scala
modules/extras-testing-tools-effectie/shared/src/test/scala/extras/testing/StubToolsFxSpec.scala
modules/extras-testing-tools-effectie/shared/src/test/scala/extras/testing/TestType.scala

Close #319 - Add `extras-testing-tools-effectie` with `StubToolsFx`

Close #319 - Add extras-testing-tools-effectie with StubToolsFx

---

build.sbt

Close #322 - Upgrade effectie to `2.0.0-beta7`

Close #322 - Upgrade effectie to 2.0.0-beta7

---

modules/extras-doobie-tools-ce2/shared/src/test/scala/extras/doobie/RunWithDb.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala/extras/doobie/RunWithDb.scala

Clean up unused code

---

website/package-lock.json
website/package.json

Docs: Upgrade Docusaurus `2.2.0` => `2.3.1`

Docs: Upgrade Docusaurus 2.2.0 => 2.3.1

---

modules/extras-testing-tools-cats/shared/src/main/scala-2.13_3/extras/testing/StubToolsCats.scala
modules/extras-testing-tools-effectie/shared/src/main/scala-2.12/extras/testing/StubToolsFx.scala
modules/extras-testing-tools-effectie/shared/src/main/scala-2.13_3/extras/testing/StubToolsFx.scala

Close #329 - Optimize `StubToolsCats` and `StubToolsFx`

Close #329 - Optimize StubToolsCats and StubToolsFx

---

modules/extras-circe/shared/src/main/scala/extras/circe/codecs/decoder.scala
modules/extras-circe/shared/src/test/scala/extras/circe/codecs/decoderSpec.scala

Close #333 - [`extras-circe`] Add `renameFields` for `Decoder` to rename circe `Json` fields

Close #333 - [`extras-circe`] Add `renameFields` for `Decoder` to rename circe `Json` fields

---

modules/extras-circe/shared/src/main/scala/extras/circe/codecs/codec.scala
modules/extras-circe/shared/src/test/scala/extras/circe/codecs/codecSpec.scala
modules/extras-circe/shared/src/test/scala/extras/circe/codecs/decoderSpec.scala
modules/extras-circe/shared/src/test/scala/extras/circe/codecs/encoderSpec.scala

Close #336 - [`extras-circe`] Add `renameFields` for `Codec` to rename circe `Json` fields

Close #336 - [`extras-circe`] Add `renameFields` for `Codec` to rename circe `Json` fields

---

build.sbt

Close #341 - Upgrade effectie to `2.0.0-beta8`

Close #341 - Upgrade effectie to 2.0.0-beta8

---

modules/extras-render/shared/src/main/scala/extras/render/Render.scala
modules/extras-render/shared/src/test/scala/extras/render/RenderSpec.scala

Close #344 - [`extras-render`] Add `contramap` to `Render`

Close #344 - [`extras-render`] Add `contramap` to `Render`

---

docs/extras-render/render.md

Update: docs - `Render.contramap`

Update: docs - `Render.contramap`

---

changelogs/0.36.0.md
docs/extras-cats/f-either-ab.md
docs/extras-cats/f-option-a.md
docs/extras-cats/optiont.md

Update: docs with more extension methods for `F[Option[A]]` and `F[Either[A, B]]`

Update: docs with more extension methods for `F[Option[A]]` and `F[Either[A, B]]`

---

build.sbt
docs/extras-concurrent/_category_.json
docs/extras-reflects/_category_.json
docs/extras-testing-tools/cats/_category_.json
docs/extras-testing-tools/cats/cats.md
docs/extras-testing-tools/common/_category_.json
docs/extras-testing-tools/common/extras-testing-tools.md
docs/extras-testing-tools/common/testing-tools.md
docs/extras-testing-tools/effectie/_category_.json
docs/extras-testing-tools/effectie/effectie.md

Update: docs - Add docs for `extras-testing-tools`, `extras-testing-tools-cats` and `extras-testing-tools-effectie`

Update: docs - Add docs for `extras-testing-tools`, `extras-testing-tools-cats` and `extras-testing-tools-effectie`

---

docs/common/intro.md
docs/extras-hedgehog/extras-hedgehog-ce3/_category_.json

Update: docs - Update `intro.md` and make `extras-hedgehog-ce3` side menu collapsed

Update: docs - Update `intro.md` and make `extras-hedgehog-ce3` side menu collapsed

---

build.sbt
modules/extras-doobie-newtype-ce2/shared/src/main/scala/extras/doobie/newtype/package.scala
modules/extras-doobie-newtype-ce2/shared/src/test/scala/extras/doobie/newtype/data.scala
modules/extras-doobie-newtype-ce2/shared/src/test/scala/extras/doobie/newtype/newtypeSpec.scala
modules/extras-doobie-newtype-ce3/shared/src/main/scala/extras/doobie/newtype/package.scala
modules/extras-doobie-newtype-ce3/shared/src/test/scala/extras/doobie/newtype/data.scala
modules/extras-doobie-newtype-ce3/shared/src/test/scala/extras/doobie/newtype/newtypeSpec.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala-2/extras/doobie/ce2/data.scala
modules/extras-doobie-tools-ce2/shared/src/test/scala-3/extras/doobie/ce2/data.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala-2/extras/doobie/ce3/data.scala
modules/extras-doobie-tools-ce3/shared/src/test/scala-3/extras/doobie/ce3/data.scala

Close #378 - Add `newtype` support for `doobie`

Close #378 - Add newtype support for doobie

---

project/plugins.sbt

Bump `sbt-wartremover` to `3.0.11`

Bump sbt-wartremover to 3.0.11

---

build.sbt
modules/extras-testing-tools-effectie/shared/src/main/scala-2.13_3/extras/testing/StubToolsFx.scala
project/plugins.sbt

Update: project config

---

docs/common/intro.md
docs/extras-render/extras-render.md
website/src/pages/index.js

Update: docs - add how to get `extras-render-refined`

Update: docs - add how to get `extras-render-refined`

---

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/OptionSyntax.scala
modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala
modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/OptionSyntaxSpec.scala

Close #384 - [`extras-cats`] Add `innerForeach` and `innerForeachF` to `OptionSyntax`

Close #384 - [extras-cats] Add innerForeach and innerForeachF to OptionSyntax

---

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/EitherSyntax.scala
modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/EitherSyntax.scala
modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/EitherSyntaxSpec.scala

Close #386 - [`extras-cats`] Add `innerForeach` and `innerForeachF` to `EitherSyntax`

Close #386 - [`extras-cats`] Add `innerForeach` and `innerForeachF` to `EitherSyntax`

---

docs/extras-cats/f-either-ab.md
docs/extras-cats/f-option-a.md

Update: docs - `f-either-ab.md` and `f-option-a.md` with `innerForeach` and `innerForeachF`

Update: docs - `f-either-ab.md` and `f-option-a.md` with `innerForeach` and `innerForeachF`

---

project/plugins.sbt

Upgrade sbt-wartremover 3.0.11 => 3.1.0

Upgrade sbt-wartremover 3.0.11 => 3.1.0

---

codecov.yml

Update: `codecov.yml` - with PR comment layout

Update: codecov.yml - with PR comment layout

---

README.md

Update: `README.md` - Update Codecov graph

Update: `README.md` - Update Codecov graph

---

README.md

Update: `README.md` - Update Codecov test coverage chart

Update: `README.md` - Update Codecov test coverage chart

---

project/build.properties

Bump sbt 1.8.2 => 1.8.3

---

.scalafix-scala2.conf

Update: `.scalafix-scala2.conf` - Remove `RemoveUnused`

Update: .scalafix-scala2.conf - Remove RemoveUnused

---

project/build.properties

Bump sbt to 1.9.0

---

build.sbt
project/build.properties

Close #399 - Upgrade sbt to `1.9.3`

Close #399 - Upgrade sbt to `1.9.3`

---

.scalafix-scala3.conf
build.sbt
project/plugins.sbt

Bump `sbt-scalafix` to `0.11.0` / xuwei-k's `scalafix-rules` to `0.3.0`

Bump `sbt-scalafix` to `0.11.0` / xuwei-k's `scalafix-rules` to `0.3.0`

---

build.sbt

Close #402 - Upgrade effectie to `2.0.0-beta11`

Close #402 - Upgrade effectie to `2.0.0-beta11`

---

docs/extras-scala-io/color.md

Update: docs - `color.md` with import `color`

Update: docs - `color.md` with import `color`

---

build.sbt

Close #406 - Add `extras-string`

Close #406 - Add `extras-string`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/numeric.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/numericSpec.scala

Close #408 - Add `syntax` for `Int` and add `toOrdinal`

Close #408 - Add `syntax` for `Int` and add `toOrdinal`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/strings.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/stringsSpec.scala

Close #420 - [`extras-string`] Add `serialCommaWith` syntax for `Seq[String]`

Close #420 - [`extras-string`] Add `serialCommaWith` syntax for `Seq[String]`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/strings.scala

`strings.scala` - update comments

`strings.scala` - update comments

---

docs/extras-string/strings.md

Update: docs - strings.md: Add `commaAnd` and `serialCommaAnd`

Update: docs - strings.md: Add `commaAnd` and `serialCommaAnd`

---

docs/extras-string/strings.md

Update: docs - `strings.md`: Add `commaOr` and `serialCommaOr`
[skip ci]

Update: docs - `strings.md`: Add `commaOr` and `serialCommaOr`

---

build.sbt

Close #433 - Upgrade effectie to `2.0.0-beta12`

Close #433 - Upgrade effectie to `2.0.0-beta12`

---

project/build.properties

Bump sbt to `1.9.6`

---

build.sbt

Close #438 - Upgrade effectie to `2.0.0-beta13`

Close #438 - Upgrade effectie to `2.0.0-beta13`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala

Close #451 - [`extras-string`] Add `String.splitByCase`

Close #451 - [`extras-string`] Add `String.splitByCase`

---

modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala

Update test code

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala

Close #447 - [`extras-string`] Add case conversion - `Seq[String].mkPascalCaseString`

Close #447 - [`extras-string`] Add case conversion - `Seq[String].mkPascalCaseString`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala

Close #455 - [`extras-string`] Add case conversion - `string.toOnePascalCase`

Close #455 - [`extras-string`] Add case conversion - `string.toOnePascalCase`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala

Close #443 - [`extras-string`] Fix `string.toPascalCase`

Close #443 - [`extras-string`] Fix `string.toPascalCase`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala

Close #444 - [`extras-string`] Add case conversion - `string.toCamelCase`

Close #444 - [`extras-string`] Add case conversion - `string.toCamelCase`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/Gens.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/StringCaseOpsSpec.scala

Close #445 - [`extras-string`] Add case conversion - `string.toSnakeCase`

Close #445 - [`extras-string`] Add case conversion - `string.toSnakeCase`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/ToSnakeUpperCaseSpec.scala

Close #465 - [`extras-string`] Add case conversion - `string.toSnakeUpperCase`

Close #465 - [`extras-string`] Add case conversion - `string.toSnakeUpperCase`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/ToSnakeLowerCaseSpec.scala

Close #466 - [`extras-string`] Add case conversion - `string.toSnakeLowerCase`

Close #466 - [`extras-string`] Add case conversion - `string.toSnakeLowerCase`

---

modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/ToSnakeCaseSpec.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/ToSnakeLowerCaseSpec.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/ToSnakeUpperCaseSpec.scala

Fix incorrect test names

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/ToKebabCaseSpec.scala

Close #446 - [`extras-string`] Add case conversion - `string.toKebabCase`

Close #446 - [`extras-string`] Add case conversion - `string.toKebabCase`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/ToKebabUpperCaseSpec.scala

Close #467 - [`extras-string`] Add case conversion - `string.toKebabUpperCase`

Close #467 - [`extras-string`] Add case conversion - `string.toKebabUpperCase`

---

website/docusaurus.config.js

Update: `docusaurus.config.js` with Google Analytics G4 setup

Update: `docusaurus.config.js` with Google Analytics G4 setup

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringSeqCaseOpsSpec/MkSnakeCaseStringSpec.scala

Close #449 - [`extras-string`] Add case conversion - `Seq[String].mkSnakeCaseString`

Close #449 - [`extras-string`] Add case conversion - `Seq[String].mkSnakeCaseString`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringSeqCaseOpsSpec/MkSnakeUpperCaseStringSpec.scala

Close #478 - [`extras-string`] Add case conversion - `Seq[String].mkSnakeUpperCaseString`

Close #478 - [`extras-string`] Add case conversion - `Seq[String].mkSnakeUpperCaseString`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringSeqCaseOpsSpec/MkSnakeLowerCaseStringSpec.scala

Close #479 - [`extras-string`] Add case conversion - `Seq[String].mkSnakeLowerCaseString`

Close #479 - [`extras-string`] Add case conversion - `Seq[String].mkSnakeLowerCaseString`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringSeqCaseOpsSpec/MkKebabLowerCaseStringSpec.scala

Close #481 - [`extras-string`] Add case conversion - `Seq[String].mkKebabLowerCaseString`

Close #481 - [`extras-string`] Add case conversion - `Seq[String].mkKebabLowerCaseString`

---

modules/extras-string/shared/src/main/scala/extras/strings/syntax/all.scala

Issue #441 - [extras-string] Add `extras.strings.syntax.cases` to `extras.strings.syntax.all`

Issue #441 - [extras-string] Add `extras.strings.syntax.cases` to `extras.strings.syntax.all`

---

changelogs/0.44.0.md

* [`extras-string`] Add `extras.strings.syntax.all` to have all `strings` syntax (#441)
```scala
import extras.strings.syntax.all._
```
* [`extras-string`] Add case conversion - `string.toPascalCase` (#443)
```scala
import extras.strings.syntax.cases._
// or
import extras.strings.syntax.all._
```
```scala
"Abc".toPascalCase
// Abc
```
```scala
"AbcDefGhi".toPascalCase
// AbcDefGhi
```
```scala
"abcDefGhi".toPascalCase
// AbcDefGhi
```
```scala
"abc".toPascalCase
// Abc
```
```scala
"ABC".toPascalCase
// Abc
```
```scala
"abc_def_ghi".toPascalCase
// AbcDefGhi
```
```scala
"abc-def-ghi".toPascalCase
// AbcDefGhi
```
```scala
"abc def ghi".toPascalCase
// AbcDefGhi
```
* [`extras-string`] Add case conversion - `string.toOnePascalCase` (#455)
```scala
import extras.strings.syntax.cases._
// …
```

extras v0.44.0

---

docs/extras-string/cases.md
docs/extras-string/numeric.md
docs/extras-string/strings.md

Update docs - `cases.md` - `cases` syntax from extras-string

Update docs - `cases.md` - `cases` syntax from extras-string

---

docs/extras-string/cases.md

Update docs - `cases.md` - `Seq[String]` to `PascalCaseString`

Update docs - `cases.md` - `Seq[String]` to `PascalCaseString`

---

docs/extras-string/cases.md

Update docs - `cases.md` - `Seq[String]` to `Snake_Case_String`

Update docs - `cases.md` - `Seq[String]` to `Snake_Case_String`

---

docs/extras-string/cases.md

* Update docs - `cases.md` - `Seq[String]` to `SNAKE_UPPER_CASE_STRING`
* Update docs - `cases.md` - `Seq[String]` to `snake_lower_case_string`
* Update docs - `cases.md` - `Seq[String]` to `Kebab-Case-String`

Update docs - `cases.md` - `Seq[String]` to `SNAKE_UPPER_CASE_STRING`, `snake_lower_case_string` and  `Kebab-Case-String`, 

---

docs/extras-string/cases.md

Update docs - cases.md - `Seq[String]` to `KEBAB-UPPER-CASE-STRING`

Update docs - cases.md - `Seq[String]` to `KEBAB-UPPER-CASE-STRING`

---

docs/extras-string/cases.md

Update docs - `cases.md` - `Seq[String]` to `kebab-lower-case-string`

Update docs - cases.md - `Seq[String]` to `kebab-lower-case-string`

---

docs/extras-string/cases.md

Update docs - `cases.md` - more examples to case changes for `Seq[String]`

Update docs - `cases.md` - more examples to case changes for `Seq[String]`

---

docs/extras-string/cases.md

Update docs - cases.md - Split `String` by `PascalCase` or `cacmelCase`

Update docs - cases.md - Split `String` by `PascalCase` or `cacmelCase`

---

build.sbt
project/build.properties
project/plugins.sbt

Bump sbt to 1.9.8

---

build.sbt

Close #508 - Upgrade effectie to `2.0.0-beta14`

Close #508 - Upgrade effectie to `2.0.0-beta14`

---

website/docusaurus.config.js

Update docs: Make the sidebar hidable

Update docs: Make the sidebar hidable

---

project/plugins.sbt

Bump sbt-devoops to 3.1.0 / sbt-docusaur to 0.16.0

Bump sbt-devoops to 3.1.0 / sbt-docusaur to 0.16.0

---

.gitignore

Update .gitignore to exclude additional build tool files

Update .gitignore to exclude additional build tool files

---

build.sbt
docs/extras-refinement/syntax/refinement.md
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerSyntaxSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerWithIoSpec.scala
modules/extras-hedgehog-ce3/shared/src/test/scala/extras/hedgehog/ce3/ManualCatsEffectRunnerWithIoSyntaxSpec.scala
modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/truecolor/Rainbow.scala
modules/extras-testing-tools/shared/src/main/scala/extras/testing/StubTools.scala
project/plugins.sbt

Updated sbt plugin and Scala versions, and refactored the rainbow color logic

Updated sbt plugin and Scala versions, and refactored the rainbow color logic

---

build.sbt

Close #526 - Upgrade `effectie` to `2.0.0`

Close #526 - Upgrade `effectie` to `2.0.0`

---

.github/workflows/dependency-graph.yml

Update GitHub Actions: Add `sbt/setup-sbt` to dependency-graph workflow

Update GitHub Actions: Add `sbt/setup-sbt` to dependency-graph workflow

---

project/plugins.sbt

Bump `sbt-devoops` to `3.2.1`

---

README.md
docs/common/intro.md

Update: docs - `README.md` and intro.md with the Maven Central badges

Update: docs - `README.md` and intro.md with the Maven Central badges

---

.jvmopts

Remove `.jvmopts`

---

project/build.properties

Bump sbt to 1.11.5

---

modules/extras-core/shared/src/main/scala-3/extras/core/syntax/all.scala
modules/extras-core/shared/src/main/scala-3/extras/core/syntax/predefs.scala
modules/extras-core/shared/src/test/scala-3/extras/core/syntax/predefsSpec.scala

Close #580: [`extras-core`] Add the Elvis operator (`?:`) to `extras.core.syntax` for Scala 3

Close #580: [`extras-core`] Add the Elvis operator (`?:`) to `extras.core.syntax` for Scala 3

---

project/build.properties

Bump `sbt` to `1.11.6`
