build.sbt, extras-scala-io/src/main/scala-2/extras/scala/io/Color.scala, extras-scala-io/src/main/scala-3/extras/scala/io/Color.scala, extras-scala-io/src/test/scala-2/extras/scala/io/ColorSpec.scala, extras-scala-io/src/test/scala-3/extras/scala/io/ColorSpec.scala, extras-scala-io/src/test/scala/extras/scala/io/ColorTestUtils.scala
Close #26 - Add typed version of `scala.io.AnsiColor` to `extras-scala-io`
=> Close #26 - Add typed version of scala.io.AnsiColor to extras-scala-io

build.sbt, extras-scala-io/src/main/scala-2.11_2.12/extras/scala/io/CanClose.scala, extras-scala-io/src/main/scala-2.13/extras/scala/io/CanClose.scala, extras-scala-io/src/main/scala-3/extras/scala/io/CanClose.scala, extras-scala-io/src/test/scala-2.11_2.12/extras/scala/io/CanCloseSpec.scala, extras-scala-io/src/test/scala-2.13/extras/scala/io/CanCloseSpec.scala, extras-scala-io/src/test/scala-3/extras/scala/io/CanCloseSpec.scala
Close #28 - `CanClose[A]` type class as an alternative to `AutoCloseable`
=> Close #28 - CanClose[A] type class as an alternative to AutoCloseable

build.sbt
Changed the default `scalaVersion` back to 2
=> Changed the default scalaVersion back to 2

extras-cats/src/main/scala-2/extras/cats/syntax/EitherSyntax.scala, extras-cats/src/main/scala-2/extras/cats/syntax/OptionSyntax.scala, extras-cats/src/main/scala-3/extras/cats/syntax/EitherSyntax.scala, extras-cats/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala, extras-cats/src/test/scala-2/extras/cats/syntax/AllSyntaxSpec.scala, extras-cats/src/test/scala-2/extras/cats/syntax/EitherSyntaxSpec.scala, extras-cats/src/test/scala-2/extras/cats/syntax/OptionSyntaxSpec.scala, extras-cats/src/test/scala-3/extras/cats/syntax/AllSyntaxSpec.scala, extras-cats/src/test/scala-3/extras/cats/syntax/EitherSyntaxSpec.scala, extras-cats/src/test/scala-3/extras/cats/syntax/OptionSyntaxSpec.scala
Close #39 - Add a shorter name method for `eitherT`
=> Close #39 - Add a shorter name method for eitherT

changelogs/0.2.0.md
* Create the doc site (#23)(#34)
* Add `extras-scala-io` (#24)
* Add typed version of `scala.io.AnsiColor` to `extras-scala-io` (#26)
* `ColorSyntax` for typed `AnsiColor` (#27)
* `CanClose[A]` type class as an alternative to `AutoCloseable` (#28)
* Redesign `extras-concurrent-testing` APIs (#36)
* Add a shorter name method for `eitherT` (#39)
* Add `syntax` for testing `Future` (#41)
=> extras v0.2.0

.scalafmt.conf, build.sbt
Update: `.scalafmt.conf` with more specific format rules
=> Update: .scalafmt.conf with more specific format rules

extras-hedgehog-cats-effect3/src/main/scala/extras/hedgehog/cats/effect/CatsEffectRunner.scala, extras-hedgehog-cats-effect3/src/test/scala/extras/hedgehog/cats/effect/CatsEffectRunnerSpec.scala
Close #71 - Add a way to test `IO[A]` - `IO[A].completeThen(A => Result): Result`
=> Close #71 - Add a way to test IO[A] - IO[A].completeThen(A => Result): Result

extras-hedgehog-cats-effect3/src/main/scala/extras/hedgehog/cats/effect/CatsEffectRunner.scala, extras-hedgehog-cats-effect3/src/test/scala/extras/hedgehog/cats/effect/CatsEffectRunnerSpec.scala
Close #73 - Add a way to test `IO[A]` with error - `IO[A].errorThen(Throwable => Result): Result`
=> Close #73 - Add a way to test IO[A] with error - IO[A].errorThen(Throwable => Result): Result

extras-hedgehog-cats-effect3/src/main/scala/extras/hedgehog/cats/effect/CatsEffectRunner.scala, extras-hedgehog-cats-effect3/src/test/scala/extras/hedgehog/cats/effect/CatsEffectRunnerSpec.scala
Close #75 - `CatsEffectRunner.IoOps.expectError` should take `Eq` and `Show` for the expected error
=> Close #75 - CatsEffectRunner.IoOps.expectError should take Eq and Show for the expected error

changelogs/0.4.0.md
* Add a way to test `IO[A]` - `IO[A].completeThen(A => Result): Result` (#71)
* Add a way to test `IO[A]` with error - `IO[A].errorThen(Throwable => Result): Result` (#73)
* `CatsEffectRunner.IoOps.expectError` should take `Eq` and `Show` for the expected error (#75)
* Publish to [s01.oss.sonatype.org](https://s01.oss.sonatype.org) (the new Maven central) (#67)
=> extras v0.4.0

changelogs/0.5.0.md
* Set up Codecov in GitHub Actions (#83)
* Add Scalafix check (#92)
* Support Scala.js (#95)
* Move all sub-projects to `modules` (#97)
=> extras v0.5.0

changelogs/0.6.0.md
* Add syntax to support `newtype` and `refined` (#101)
* `extras-reflects` and `extras-refinement` have been added.
=> extras v0.6.0

modules/extras-refinement/shared/src/main/scala/extras/refinement/syntax/refinement.scala, modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/refinementSpec.scala
Close #105 - Change extension method for refinement type + newtype from `value.as[A].validate` to `value.validateAs[A]`
=> Close #105 - Change extension method for refinement type + newtype from `value.as[A].validate` to `value.validateAs[A]`

changelogs/0.8.0.md
* `extras-refinement`: Downgrade `refined` to `0.9.27` (#110)
=> extras v0.8.0

changelogs/0.9.0.md
* [`extras-refinement`] Replace `EitherNel` with `EitherNec` ([more performant](https://typelevel.org/blog/2018/09/04/chain-replacing-the-list-monoid.html)) (#115)
=> extras v0.9.0

changelogs/0.10.0.md
* More `syntax` for `extras-reflects` (#119)
=> extras v0.10.0

changelogs/0.11.0.md
* [`extras-reflects`] Add `A.nestedTypeName` `syntax` (#125)
=> extras v0.11.0

modules/extras-scala-io/shared/src/main/scala-2.11_2.12/extras/scala/io/file/TempFiles.scala, modules/extras-scala-io/shared/src/main/scala-2.13/extras/scala/io/file/TempFiles.scala, modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/file/TempFiles.scala, modules/extras-scala-io/shared/src/main/scala/extras/scala/io/file/ops.scala, modules/extras-scala-io/shared/src/test/scala/extras/scala/io/file/opsSpec.scala
Close #139 - [`extras-scala-io`] Change `deleteFileRecursively` to `deleteAllRecursively`
=> Close #139 - [`extras-scala-io`] Change `deleteFileRecursively` to `deleteAllRecursively`

changelogs/0.13.0.md
* [`extras-scala-io`] Change `file.ops` to `file.syntax` (#137)
* [`extras-scala-io`] Change `getAllFiles` to `listAllFilesRecursively` (#138)
* [`extras-scala-io`] Change `deleteFileRecursively` to `deleteAllRecursively` (#139)
=> extras v0.13.0

modules/extras-refinement/shared/src/main/scala/extras/refinement/syntax/refinement.scala, modules/extras-refinement/shared/src/test/scala/extras/refinement/syntax/refinementSpec.scala
Close #149 - Add `toValue` for `newtype` containing `refined` type to get the underlying value
=> Close #149 - Add `toValue` for `newtype` containing `refined` type to get the underlying value

changelogs/0.14.0.md
* Add `toValue` for `newtype` containing `refined` type to get the underlying value (#149)
=> extras v0.14.0

changelogs/0.15.0.md
* [`extras-scala-io`] Add more `String.color` to `color` syntax (#158)
=> extras v0.15.0

changelogs/0.16.0.md
* [`extras-scala-io`] Add `Rgb` to have true color support (#162)
```scala
Rgb.fromInt(0x000000) // Right(Rgb(0))
Rgb.fromInt(0xff0000) // Right(Rgb(16711680))
Rgb.fromInt(0x00ff00) // Right(Rgb(65280))
Rgb.fromInt(0x0000ff) // Right(Rgb(255))
Rgb.fromInt(0xffffff) // Right(Rgb(16777215))
// and more smart constructors and extension methods to get ASCII escape chars and HTML colors (hex)
```
* [`extras-scala-io`] Add a way to paint `String` with rainbow 🌈 colors (#161)
=> extras v0.16.0

modules/extras-core/shared/src/main/scala/extras/core/syntax/StringSyntax.scala, modules/extras-core/shared/src/main/scala/extras/core/syntax/package.scala, modules/extras-core/shared/src/test/scala/extras/core/syntax/StringSyntaxSpec.scala
Close #172 - [`extras-core`] Add `syntax` to encode `String` to escaped unicode chars
=> Close #172 - [`extras-core`] Add `syntax` to encode `String` to escaped unicode chars

build.sbt, modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/syntax/ColorSyntax.scala, modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/syntax/ColorSyntax.scala, modules/extras-scala-io/shared/src/test/scala/extras/scala/io/syntax/ColorSyntaxSpec.scala
Close #170 - [`extras-scala-io`] `extras.scala.io.syntax.color` `"".colored(Color)` should return `""`
=> Close #170 - [`extras-scala-io`] `extras.scala.io.syntax.color` `"".colored(Color)` should return `""`

modules/extras-scala-io/shared/src/main/scala-2/extras/scala/io/truecolor/Rgb.scala, modules/extras-scala-io/shared/src/main/scala-3/extras/scala/io/truecolor/Rgb.scala, modules/extras-scala-io/shared/src/test/scala/extras/scala/io/syntax/truecolor/RgbSyntaxSpec.scala, modules/extras-scala-io/shared/src/test/scala/extras/scala/io/truecolor/RgbSpec.scala
Close #176 - [`extras-scala-io`] `Rgb.color("")` and `Rgb.colored("")` should return `""`
Close #177 - [`extras-scala-io`] `"".rgb` and `"".rgbed` should return `""`
=> Close #176 and Close #177 - [`extras-scala-io`] `Rgb.color("")`, `Rgb.colored("")`, `"".rgb` and `"".rgbed` should return `""`

changelogs/0.17.0.md
* [`extras-core`] Add `syntax` to encode `String` to escaped unicode chars (#172)
* [`extras-scala-io`] `extras.scala.io.syntax.color` `"".colored(Color)` should return `""` (#170)
* [`extras-scala-io`] Add `color` and `colored` to `Color` (#175)
* [`extras-scala-io`] `Rgb.color("")` and `Rgb.colored("")` should return `""` (#176)
* [`extras-scala-io`] `"".rgb` and `"".rgbed` should return `""` (#177)
* [`extras-scala-io`] `Rainbow.rainbow("")` and `Rainbow.rainbowHtml("")` should return `""` (#180)
* [`extras-scala-io`] `"".rainbowed` and `"".rainbowedHtml` should return `""` (#181)
=> extras v0.17.0

changelogs/0.18.0.md
* [`extras-scala-io`] Add `Rainbow.rainbows(Seq[String])` (#186)
* [`extras-scala-io`] Add syntax: `Seq[String].rainbowed` (#188)
=> extras v0.18.0

changelogs/0.19.0.md
* [`extras-refinement`] Add `NonEmptyString` concatenation syntax (#208)
```scala
import eu.timepit.refined.types.string.NonEmptyString
import extras.refinement.syntax.string._
NonEmptyString("abc") ++ NonEmptyString("def")
// NonEmptyString("abcdef")
val givenName = NonEmptyString("Kevin")
val surname = NonEmptyString("Lee")
val fullName = givenName ++ NonEmptyString(" ") ++ surname
// NonEmptyString("Kevin Lee")
```
* [`extras-refinement`] Add `all` syntax to refinement (#210)
```scala
import extras.refinement.syntax.all._
```
is equivalent to
```scala
import extras.refinement.syntax.refinement._
import extras.refinement.syntax.string._
```
* Upgrade docs site to Docusaurus `2.0.0-rc.1` (#195)
* Upgrade docs site to Docusaurus `2.0.1` (#206)
* [docs] Add `Fira Code Nerd Font` and …
=> extras v0.19.0

changelogs/0.20.0.md
* Rename `extras-hedgehog-cats-effect3` to `extras-hedgehog-ce3` (#215)
* [`extras-hedgehog-ce3`] Add support for test returning `IO[Result]` (#216)
* [`extras-hedgehog-ce3`] Rename `withIO` to `runIO` in `CatsEffectRunner` (#221)
```scala
def testSomething: Property =
for {
n <- Gen.int(Range.linear(Int.MinValue, Int.MaxValue)).log("n")
} yield runIO { // withIO: (=> IO[Result]) => Result
// Manual implicit Ticker creation is no longer required.
val expected = n
val actual   = IO(n)
actual.map(_ ==== expected) // IO[Result]
}
```
* [`extras-hedgehog-ce3`] Add `withIO` with `implicit ticker =>` (#223)
```scala
def testSomething: Property =
for {
n <- Gen.int(Range.linear(Int.MinValue, Int.MaxValue)).log("n")
} yield withIO { implicit ticker =>
val expected = n
val actual   = IO(n) …
```
=> extras v0.20.0

changelogs/0.21.0.md
* Drop support for Scala `2.11` (#236)
* [`extras-core`] Add `Render[A]` type-class (#234)
* [`extras-core`] Add syntax for `Render[A]` type-class (#238)
* Add `sbt-dependency-submission` GitHub workflow (#231)
=> extras v0.21.0

changelogs/0.21.1.md
* Fix `Iterable[A].renderString` renders only the first element (#243)
=> extras v0.21.1

changelogs/0.22.0.md
* Modularise `extras-render` (#248)
=> extras v0.22.0

modules/extras-render/shared/src/main/scala/extras/render/Render.scala, modules/extras-render/shared/src/main/scala/extras/render/syntax.scala, modules/extras-render/shared/src/test/scala/extras/render/syntaxSpec.scala
Close #253 - [`extras-render`] Add `String` interpolation support for `Render`
=> Close #253 - [`extras-render`] Add `String` interpolation support for `Render`

changelogs/0.23.0.md
* Rename `extras.render.syntax.render` => `extras.render.syntax` (#252)
* [`extras-render`] Add `String` interpolation support for `Render` (#253)
```scala
import extras.render.Render
import extras.render.syntax._
final case class Foo(id: Int, name: String)
object Foo {
implicit val fooRender: Render[Foo] =
foo => s"{ID=${foo.id.toString},Name=${foo.name}}"
}
val foo1 = Foo(1, "A")
val foo2 = Foo(2, "B")
val foo3 = Foo(3, "C")
println(render"$foo1 > $foo2 >> $foo3")
// {ID=1,Name=A} > {ID=2,Name=B} >> {ID=3,Name=C}
```
* [`extras-render`] Add `Render.render[A](A => String): Render[A]` (#256)
```scala
import extras.render.Render
final case class Something(value: String)
object Something {
implicit val renderSomething: Render[Something] =
Render.render(s => s"value=${s.value}")
}
val foo = …
```
=> extras v0.23.0

modules/extras-type-info/shared/src/main/scala-2/extras/typeinfo/syntax/types.scala, modules/extras-type-info/shared/src/test/scala-2/extras/typeinfo/syntax/typesSpec.scala
Fix #264 - `extras.typeinfo.syntax.tags` => `extras.typeinfo.syntax.types` (tags was the wrong name)
=> Fix #264 - extras.typeinfo.syntax.tags => extras.typeinfo.syntax.types (tags was the wrong name)

build.sbt, modules/extras-hedgehog-circe/shared/src/main/scala-2/extras/hedgehog/circe/RoundTripTester.scala, modules/extras-hedgehog-circe/shared/src/main/scala-3/extras/hedgehog/circe/RoundTripTester.scala, modules/extras-hedgehog-circe/shared/src/test/scala/extras/hedgehog/circe/RoundTripTesterSpec.scala
Close #270 - [`extras-hedgehog-circe`] Use `extras-type-info` to support Scala 3
- Scala 2 version uses `extras-type-info` as well, but `extras-type-info` internally uses `WeakTypeTag` from `scala.reflect.runtime.universe` in `scala-reflect`, an additional reflection API library, to get the type info.
- Scala 3 version of `extras-type-info` uses `scala.reflect.ClassTag`, `scala.compiletime` and `scala.quoted` to get the type info.
=> Close #270 - [`extras-hedgehog-circe`] Use `extras-type-info` to support Scala 3

changelogs/0.24.0.md
* [`extras-type-info`] Add `extras-type-info` module to replace `extras-reflects` with Scala 3 support (#264)
```scala
sealed trait Aaa
object Aaa {
final case class Bbb(n: Int) extends Aaa
case object Ccc extends Aaa
def bbb(n: Int): Aaa = Bbb(n)
def ccc: Aaa         = Ccc
}
final case class Something[A](a: A)
Aaa.bbb(123).nestedClassName
// Aaa.Bbb
Aaa.ccc.nestedTypeName
// Aaa.Ccc
```
* [`extras-hedgehog-circe`] Add `round-trip` test support for circe (#263)
```scala
object SomethingSpec extends Properties {
override def tests: List[Test] = List(
property("round-trip test Codec[Something]", roundTripTestCodecSomething)
)
def roundTripTestCodecSomething: Property =
for {
something <- genSomething.log("something")
} yield {
RoundTripTester(something)
.indent(2)
.test()
}
def …
```
=> extras v0.24.0

changelogs/0.25.0.md
* [`extras-type-info`] Release `extras-type-info` (#273)
```scala
sealed trait Aaa
object Aaa {
final case class Bbb(n: Int) extends Aaa
case object Ccc extends Aaa
def bbb(n: Int): Aaa = Bbb(n)
def ccc: Aaa         = Ccc
}
final case class Something[A](a: A)
Aaa.bbb(123).nestedClassName
// Aaa.Bbb
Aaa.ccc.nestedTypeName
// Aaa.Ccc
```
It was supposed to be released in `0.24.0` but wasn't included by mistake.
=> extras v0.25.0

.github/workflows/manual-build.yml, build.sbt
Close #284 - Bump Scala / bump libraries
- Scala 2.12.13 => 2.12.17
- Scala 2.13.6 => 2.13.10
- Scala 3.0.0 => 3.1.3
- Cats 2.6.1 and 2.7.0 => 2.8.0
- Cats Effect 2.5.4 => 2.5.5
- Cats Effect 3.2.9 => 3.3.14
Add new libraries for the future task
=> Close #284 - Bump Scala / bump libraries

changelogs/0.26.0.md
* [`extras-render-refined`] Add `newtype` + `refined` support (#277)
```scala
import eu.timepit.refined.types.string.NonEmptyString
import extras.render.Render
import io.estatico.newtype.macros.newtype
import extras.render.refined._
@newtype case class Name(value: NonEmptyString)
object Name {
implicit val nameRender: Render[Name] = deriving
}
```
instead of
```scala
@newtype case class Name(value: NonEmptyString)
object Name {
implicit val nameRender: Render[Name] = Render.render(_.value.value)
}
```
* [`extras-doobie-tools`] Add doobie tools to run SQL query (#283)
* `extras-doobie-tools-ce2`
* `extras-doobie-tools-ce3`
This is meant to be used for testing.
e.g.)
```scala
DbTools.fetchSingleRow[F][Example](
sql"""
SELECT id, name, note
FROM db_tools_test.example
"""
)(transactor) // …
```
=> extras v0.26.0

changelogs/0.27.0.md
* [`extras-circe`]: Add an extension method to circe `Encoder` to add more fields (#291)
```scala
import io.circe._
import io.circe.generic.semiauto._
final case class Something(n: Int) {
def name: String = "Blah"
}
object Something {
implicit val somethingEncoder: Encoder[Something] = deriveEncoder
}
Something(1).asJson.spaces2
```
results in
```json
{
"n": 1
}
```
There should be an easy way to add the `name` field to have JSON like
```json
{
"n": 1,
"name": "Blah"
}
```
For instance,
```scala
import extras.circe.codecs.encoder._
object Something {
implicit val somethingEncoder: Encoder[Something] =
deriveEncoder.withFields { something =>
List("name" -> something.name.asJson)
}
}
```
* [`extras-fs2-v2-text`][`extras-fs2-v3-text`]: Add fs2 syntax to compile `Stream[F, Byte]` to …
=> extras v0.27.0

modules/extras-fs2-v2-text/shared/src/main/scala-2/extras/fs2/text/syntax.scala, modules/extras-fs2-v2-text/shared/src/main/scala-3/extras/fs2/text/syntax.scala, modules/extras-fs2-v2-text/shared/src/test/scala/extras/fs2/text/syntaxSpec.scala, modules/extras-fs2-v3-text/shared/src/main/scala-2/extras/fs2/text/syntax.scala, modules/extras-fs2-v3-text/shared/src/main/scala-3/extras/fs2/text/syntax.scala, modules/extras-fs2-v3-text/shared/src/test/scala/extras/fs2/text/syntaxSpec.scala
Close #304 - [`extras-fs2-v2-text`][`extras-fs2-v3-text`]: Replace the implicit param, `Sync`, for `utf8String` from `extras.fs2.text.syntax` with `Compiler`
=> Close #304 - [extras-fs2-v2-text][extras-fs2-v3-text]: Replace the implicit param, Sync, for utf8String from extras.fs2.text.syntax with Compiler

changelogs/0.28.0.md
* [`extras-fs2-v2-text`][`extras-fs2-v3-text`]: Replace the implicit param, `Sync`, for `utf8String` from `extras.fs2.text.syntax` with `Compiler` (#304)
So the following method 
```scala
def utf8String(implicit sync: Sync[F]): F[String]
```
has been changed to
```scala
def utf8String(implicit compiler: Compiler[F, F]): F[String]
```
fs2 v2: `fs2.Stream.Compiler` / fs2 v3: `fs2.Compiler`
=> extras v0.28.0

build.sbt
Update `build.sbt` - remove unnecessary duplicate libraries
=> Update build.sbt - remove unnecessary duplicate libraries

changelogs/0.29.0.md
* Add [`extras-testing-tools`] and [`extras-testing-tools-cats`] with tools to use stub (#307)
```scala
import extras.testing.StubTools
trait TestType {
def foo(n: Int): Int
}
object TestTypeStub {
def apply(f: => Option[Int => Int]): TestType = new TestType {
override def foo(n: Int): Int =
f.fold[Int](throw StubTools.missing)(_(n))
}
}
```
If the stub function is missing, it will throw a `MissingStubException` saying where the missing stub is.
For example,
```scala
TestTypeStub(None)
```
results in
```
>> Missing Stub implementation at
>>   extras.testing.TestTypeStub$$anon$1.$anonfun$foo$1(TestType.scala:11)
>>   ---
>>   Details:
>>   extras.testing.TestTypeStub$$anon$1.$anonfun$foo$1(TestType.scala:11)
at scala.Option.fold(Option.scala:263)
at …
```
=> extras v0.29.0

build.sbt
Close #314 - Upgrade `effectie` to `2.0.0-beta6`
=> Close #314 - Upgrade `effectie` to `2.0.0-beta6`

changelogs/0.30.0.md
* Upgrade `effectie` to `2.0.0-beta6` (#314)
=> extras v0.30.0

docs/common/intro.md
Update: docs - fix incorrect module names
=> Update: docs - fix incorrect module names

changelogs/0.31.0.md
* Add `extras-testing-tools-effectie` with `StubToolsFx` (#319)
```scala
import cats._
import effectie.core._
trait TestType[F[*]] {
def foo(n: Int): F[Int]
def bar(n: Int): F[Int]
}
object TestTypeStub {
def apply[F[*]: Fx: Monad](f4Foo: => Option[Int => Int], f4Bar: => Option[Int => F[Int]]): TestType[F] =
new TestType[F] {
override def foo(n: Int): F[Int] =
StubToolsFx.stub(f4Foo).map(_(n))
override def bar(n: Int): F[Int] =
StubToolsFx.stub(f4Bar).flatMap(_(n))
}
}
```
If the stub function is missing, it will be `F` containing `MissingStubException` saying where the missing stub is.
For example, the following code
```scala
import effectie.instances.ce2.fx._
val testType = TestTypeStub[IO](none, f.some)
testType.foo(n).catchNonFatalThrowable // IO[Either[Throwable, Int]]
```
results in …
=> extras v0.31.0

.scalafmt.conf, build.sbt, modules/extras-render/shared/src/main/scala/extras/render/syntax.scala, project/plugins.sbt
Close #324 - Upgrade sbt-plugins
* `sbt-scalafmt` to `2.5.0`
* `scalafmt` to `3.7.2`
* `sbt-scoverage` to `2.0.7`
* `sbt-mdoc` to `2.3.7`
* `sbt-tpolecat` to `0.4.2`
* `scalafix-rules` to `0.2.15`
* `sbt-scalajs` to `1.13.0`
=> Close #324 - Upgrade sbt-plugins

changelogs/0.32.0.md
* Upgrade `effectie` to `2.0.0-beta7` (#322)
* Upgrade sbt-plugins (#324)
* `sbt-scalafmt` to `2.5.0`
* `scalafmt` to `3.7.2`
* `sbt-scoverage` to `2.0.7`
* `sbt-mdoc` to `2.3.7`
* `sbt-tpolecat` to `0.4.2`
* `scalafix-rules` to `0.2.15`
* `sbt-scalajs` to `1.13.0`
=> extras v0.32.0

modules/extras-circe/shared/src/main/scala/extras/circe/codecs/encoder.scala, modules/extras-circe/shared/src/test/scala/extras/circe/codecs/encoderSpec.scala
Close #331 - [`extras-circe`] Add `renameFields` for `Encoder` to rename circe `Json` fields
=> Close #331 - [`extras-circe`] Add `renameFields` for `Encoder` to rename circe `Json` fields

build.sbt, modules/extras-circe/shared/src/main/scala/extras/circe/codecs/encoder.scala, modules/extras-circe/shared/src/test/scala/extras/circe/codecs/encoderSpec.scala
Close #335 - [`extras-circe`] `renameFields` for `Encoder` should fail encoding when new name conflicts with the existing name
=> Close #335 - [`extras-circe`] `renameFields` for `Encoder` should fail encoding when new name conflicts with the existing name

changelogs/0.33.0.md
* [`extras-circe`] Add `renameFields` for `Encoder` to rename circe `Json` fields (#331)
```scala
final case class Something(a: Int, b: String, price: BigDecimal, c: Boolean)
object Something {
import extras.circe.codecs.encoder._
implicit val somethingEncoder: Encoder[Something] =
deriveEncoder[Something].renameFields(
"a"  -> "productNumber",
"b"  -> "name",
"c" -> "inStock",
)
}
import io.circe.syntax._
Something(1, "Vibranium Shield", BidDecimal(9999999), false).asJson.spaces2
```
```json
{
"id": 1,
"name": "Vibranium Shield",
"price": 9999999,
"inStock": false
}
```
* [`extras-circe`] `renameFields` for `Encoder` should fail encoding when new name conflicts with the existing name (#335)
```scala
final case class Something(n: Int, s: String, name: String)
object Something {
import …
```
=> extras v0.33.0

docs/common/intro.md, docs/extras-circe/codecs-codec.md, docs/extras-circe/codecs-encoder.md
Update: docs - with new extension methods to `Encoder`, `Decoder` and `Codec` in circe
=> Update: docs - with new extension methods to `Encoder`, `Decoder` and `Codec` in circe

changelogs/0.34.0.md
* Upgrade `effectie` to `2.0.0-beta8` (#341)
=> extras v0.34.0

changelogs/0.35.0.md
* [`extras-render`] Add `contramap` to `Render` (#344)
```scala
import java.util.UUID
import extras.render.Render
final case class Id(value: UUID) extends AnyVal
object Id {
implicit val idRender: Render[Id] = Render[UUID].contramap(_.value)
}
```
=> extras v0.35.0

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/OptionSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/OptionSyntaxSpec.scala
Close #348 - [`extras-cats`] Add `innerMap` extension method to `F[Option[A]]`
=> Close #348 - [`extras-cats`] Add `innerMap` extension method to `F[Option[A]]`

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/OptionSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/OptionSyntaxSpec.scala
Close #349 - [`extras-cats`] Add `innerFlatMap` extension method to `F[Option[A]]`
=> Close #349 - [`extras-cats`] Add `innerFlatMap` extension method to `F[Option[A]]`

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/OptionSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/OptionSyntaxSpec.scala
Close #352 - [`extras-cats`] Add `innerFlatMapF` extension method to `F[Option[A]]`
=> Close #352 - [`extras-cats`] Add `innerFlatMapF` extension method to `F[Option[A]]`

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala, modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/OptionSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/OptionSyntaxSpec.scala
Close #354 - [`extras-cats `] `innerGetOrElse`, `innerGetOrElseF`, `innerFold` and `innerFoldF` to extension methods to `F[Option[A]]`
=> Close #354 - [`extras-cats `] `innerGetOrElse`, `innerGetOrElseF`, `innerFold` and `innerFoldF` to extension methods to `F[Option[A]]`

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/EitherSyntax.scala, modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/EitherSyntax.scala, modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/EitherSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/EitherSyntaxSpec.scala
Close #358 - [`extras-cats`] Add `innerLeftMap`, `innerLeftFlatMap` and `innerLeftFlatMapF` extension methods to `F[Either[A, B]]`
=> Close #358 - [`extras-cats`] Add `innerLeftMap`, `innerLeftFlatMap` and `innerLeftFlatMapF` extension methods to `F[Either[A, B]]`

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/EitherSyntax.scala, modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/EitherSyntax.scala
Issue #362 - Fix type parameter of `innerCollectFirst` for `F[Either[A, B]]`
=> Issue #362 - Fix type parameter of `innerCollectFirst` for `F[Either[A, B]]`

modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/AllSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/AllSyntaxSpec.scala
Close #366 - [`extras-cats`] Add tests for all new extension methods in `AllSyntax` inherited from `OptionSyntax` and `EitherSyntax`
=> Close #366 - [`extras-cats`] Add tests for all new extension methods in `AllSyntax` inherited from `OptionSyntax` and `EitherSyntax`

changelogs/0.36.0.md
* Add `innerMap` extension method to `F[Option[A]]` (#348)
```scala
val foa: F[Option[A]] = ...
foa.innerMap(A => B) // F[Option[B]]
```
```scala
val foa: IO[Option[Int]] = IO.pure(1)
// IO[Option[Int]] = IO(Some(1))
foa.innerMap(_ + 999)
// IO[Option[Int]] = IO(Some(1000))
```
***
* Add `innerFlatMap` extension method to `F[Option[A]]` (#349)
```scala
val foa: F[Option[A]] = ...
foa.innerFlatMap(A => Option[B]) // F[Option[B]]
```
```scala
val foa: IO[Option[Int]] = IO.pure(1)
// IO[Option[Int]] = IO(Some(1))
foa.innerFlatMap((_ + 999).some)
// IO[Option[Int]] = IO(Some(1000))
```
***
* Add `innerFlatMapF` extension method to `F[Option[A]]` (#352)
```scala
val foa: F[Option[A]] = ...
foa.innerFlatMapF(A => F[Option[B]]) // F[Option[B]]
```
```scala
val foa: IO[Option[Int]] = IO.pure(1) …
```
=> extras v0.36.0

modules/extras-cats/shared/src/main/scala-2/extras/cats/syntax/EitherSyntax.scala, modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/EitherSyntax.scala, modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/AllSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-2/extras/cats/syntax/EitherSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/AllSyntaxSpec.scala, modules/extras-cats/shared/src/test/scala-3/extras/cats/syntax/EitherSyntaxSpec.scala
Close #368 - [`extras-cats`] Fix `innerFold` and `innerFoldF` for `F[Either[A, B]]` to have the same method signature as `Either`'s
=> Close #368 - [`extras-cats`] Fix `innerFold` and `innerFoldF` for `F[Either[A, B]]` to have the same method signature as `Either`'s

changelogs/0.37.0.md
* [`extras-cats`] Fix `innerFold` and `innerFoldF` for `F[Either[A, B]]` to have the same method signature as `Either`'s (#368)
* `innerFold`
```scala
def innerFold[D](ifLeft: => D)(f: B => D)(implicit F: Functor[F]): F[D]
```
to
```scala
def innerFold[D](forLeft: A => D)(forRight: B => D)(implicit F: Functor[F]): F[D]
```
* `innerFoldF`
```scala
def innerFoldF[D](ifLeft: => F[D])(f: B => F[D])(implicit F: FlatMap[F]): F[D]
```
to
```scala
def innerFoldF[D](forLeft: A => F[D])(forRight: B => F[D])(implicit F: FlatMap[F]): F[D]
```
=> extras v0.37.0

docs/extras-circe/codecs-codec.md
Update: docs - fix the incorrect method name in `codecs-codec.md`
=> Update: docs - fix the incorrect method name in codecs-codec.md

build.sbt
Close #376 - Upgrade `effectie` to `2.0.0-beta9`
=> Close #376 - Upgrade effectie to 2.0.0-beta9

changelogs/0.38.0.md
* Add `newtype` support for `doobie` (#378)
* Upgrade `effectie` to `2.0.0-beta9` (#376)
=> extras v0.38.0

modules/extras-cats/shared/src/main/scala-3/extras/cats/syntax/OptionSyntax.scala
Close #384 - [`extras-cats`] Fix `implicit` => `using` for Scala 3
=> Close #384 - [`extras-cats`] Fix `implicit` => `using` for Scala 3

changelogs/0.39.0.md
* [`extras-cats`] Add `innerForeach` and `innerForeachF` to `OptionSyntax` (#384)
* [`extras-cats`] Add `innerForeach` and `innerForeachF` to `EitherSyntax` (#386)
=> extras v0.39.0

changelogs/0.40.0.md
* Upgrade `sbt` to `1.9.3` (#399)
* Upgrade `effectie` to `2.0.0-beta11` (#402)
=> extras v0.40.0

modules/extras-string/shared/src/main/scala/extras/strings/syntax/strings.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/stringsSpec.scala
Close #412 - [`extras-string`] Add `commaAnd` syntax for `Seq[String]`
=> Close #412 - [`extras-string`] Add `commaAnd` syntax for `Seq[String]`

modules/extras-string/shared/src/main/scala/extras/strings/syntax/strings.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/stringsSpec.scala
Close #414 - [`extras-string`] Add `serialCommaAnd` syntax for `Seq[String]`
=> Close #414 - [`extras-string`] Add `serialCommaAnd` syntax for `Seq[String]`

modules/extras-string/shared/src/main/scala/extras/strings/syntax/strings.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/stringsSpec.scala
Close #419 - [`extras-string`] Add `commaWith` syntax for `Seq[String]`
=> Close #419 - [extras-string] Add commaWith syntax for Seq[String]

modules/extras-string/shared/src/main/scala/extras/strings/syntax/strings.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/stringsSpec.scala
Close #416 - [`extras-string`] Add `commaOr` syntax for `Seq[String]`
=> Close #416 - [`extras-string`] Add `commaOr` syntax for `Seq[String]`

modules/extras-string/shared/src/main/scala/extras/strings/syntax/strings.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/stringsSpec.scala
Close #417 - [`extras-string`] Add `serialCommaOr` syntax for `Seq[String]`
=> Close #417 - [`extras-string`] Add `serialCommaOr` syntax for `Seq[String]`

changelogs/0.41.0.md
* Add `extras-string` module (#406)
* [`extras-string`] Add `syntax` for `Int` and add `toOrdinal` (#408)
```scala
1.toOrdinal
// String = 1st
2.toOrdinal
// String = 2nd
3.toOrdinal
// String = 3rd
4.toOrdinal
// String = 4th
...
```
```scala
(1 to 30).map(_.toOrdinal).foreach(println(_))
```
```
1st
2nd
3rd
4th
5th
6th
7th
8th
9th
10th
11th
12th
13th
14th
15th
16th
17th
18th
19th
20th
21st
22nd
23rd
24th
25th
26th
27th
28th
29th
30th
```
* [`extras-string`] Add `syntax` for `Long` and add `toOrdinal` (#409)
```scala
1L.toOrdinal
// String = 1st
2L.toOrdinal
// String = 2nd
3L.toOrdinal
// String = 3rd
4L.toOrdinal
// String = 4th
...
```
```scala
(1L to 30L).map(_.toOrdinal).foreach(println(_))
```
```
1st
2nd
3rd
4th
5th
6th
7th
8th
9th
10th
11th
12th
13th
14th
15th
16th
17th
18th
19th …
```
=> extras v0.41.0

build.sbt, docs/common/intro.md, docs/extras-circe/_category_.json, docs/extras-concurrent/_category_.json, docs/extras-doobie-tools/common/_category_.json, docs/extras-fs2/common/_category_.json, docs/extras-hedgehog/_category_.json, docs/extras-refinement/_category_.json, docs/extras-reflects/_category_.json, docs/extras-render/_category_.json, docs/extras-scala-io/_category_.json, docs/extras-string/_category_.json, docs/extras-string/extras-string.md, docs/extras-string/numeric.md, docs/extras-testing-tools/common/_category_.json, docs/extras-type-info/_category_.json
Update: docs with `extras-string`
- Add docs for `extras-string`
- Update sidebar index for `extras-string` and other module doc pages
- Add `extras-string.md` and `numeric.md`
=> Update: docs with extras-string

docs/extras-string/strings.md
Update: docs - `strings.md` - strings syntax: `commaWith` and `serialCommaWith`
[skip ci]
=> Update: docs - `strings.md` - strings syntax: `commaWith` and `serialCommaWith`

changelogs/0.42.0.md
* Upgrade effectie to `2.0.0-beta12` (#433)
=> extras v0.42.0

changelogs/0.43.0.md
* Upgrade effectie to `2.0.0-beta13` (#438)
=> extras v0.43.0

modules/extras-string/shared/src/main/scala/extras/strings/syntax/all.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/allSpec.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/numericSpec.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/stringsSpec.scala
Close #441 - [`extras-string`] Add `extras.strings.syntax.all` to have all `strings` syntax
=> Close #441 - [`extras-string`] Add `extras.strings.syntax.all` to have all `strings` syntax

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala
Close #443 - [`extras-string`] Add case conversion - `string.toPascalCase`
=> Close #443 - [`extras-string`] Add case conversion - `string.toPascalCase`

modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala
Add more tests for `String.toPascalCase` - covering `snake_case`, `kebab-case` and space separated String values
=> Add more tests for `String.toPascalCase` - covering `snake_case`, `kebab-case` and space separated String values

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec.scala
Issue #447 - Refactor `Seq[String].mkPascalCaseString` and tests
=> Issue #447 - Refactor `Seq[String].mkPascalCaseString` and tests

build.sbt, modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/Gens.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/StringSeqCaseOpsSpec.scala
Close #448 - [`extras-string`] Add case conversion - `Seq[String].mkCamelCaseString`
=> Close #448 - [`extras-string`] Add case conversion - `Seq[String].mkCamelCaseString`

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala
Re-use `String.toPascalCase` for `Seq[String].mkPascalCaseString`
=> Re-use `String.toPascalCase` for `Seq[String].mkPascalCaseString`

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringCaseOpsSpec/SplitByCaseSpec.scala
Refactor splitByCase to use `(cs: List[Char]) match { case Nil =>`
- It was an unreachable case by the old logic.
=> Refactor splitByCase to use `(cs: List[Char]) match { case Nil =>`

modules/extras-string/shared/src/main/scala/extras/strings/syntax/cases.scala, modules/extras-string/shared/src/test/scala/extras/strings/syntax/casesSpec/stringSeqCaseOpsSpec/MkKebabUpperCaseStringSpec.scala
Close #480 - [`extras-string`] Add case conversion - `Seq[String].mkKebabUpperCaseString`
=> Close #480 - [`extras-string`] Add case conversion - `Seq[String].mkKebabUpperCaseString`

build.sbt, docs/extras-refinement/syntax/refinement.md
Fix the broken mdoc build due to the missing `"-Ymacro-annotations"` in `scalacOptions`
=> Fix the broken mdoc build due to the missing "-Ymacro-annotations" in scalacOptions

build.sbt
Close #517 - Bump `hedgehog-extra` to `0.8.0`
=> Close #517 - Bump `hedgehog-extra` to `0.8.0`

docs/extras-string/numeric.md
Update docs: Add documentation for `Int.toOrdinal` and `Long.toOrdinal` methods
=> Update docs: Add documentation for `Int.toOrdinal` and `Long.toOrdinal` methods

docs/extras-string/numeric.md
Update docs: Format `Int.toOrdinal` and `Long.toOrdinal` headings
=> Update docs: Format `Int.toOrdinal` and `Long.toOrdinal` headings

docs/extras-string/strings.md
Update docs: Reorder `strings` syntax: Move `commaAnd`, `serialCommaAnd`, `commaOr` and `serialCommaOr` to before `commaWith` and `serialCommaWith`
=> Update docs: Reorder `strings` syntax: Move `commaAnd`, `serialCommaAnd`, `commaOr` and `serialCommaOr` to before `commaWith` and `serialCommaWith`

.github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, website/docusaurus.config.ts, website/package.json
Upgrade Docusaurus to version 3.8.1 and migrate to TypeScript
- Bump Node version to build the doc site to 22.17.0
- Convert docusaurus.config.js to TypeScript (docusaurus.config.ts)
- Update dependencies to latest versions:
- Docusaurus core and preset-classic from 2.3.1 to 3.8.1
- React and React DOM to version 19.0.0
- prism-react-renderer to version 2.3.0
- Other dependencies updated to compatible versions
- Increase minimum Node.js requirement from 16.14 to 18.0
- Add typecheck script to package.json
=> Upgrade Docusaurus to version 3.8.1 and migrate to TypeScript

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/release.yml
Update GitHub Actions: Refactor GitHub workflow triggers
- Change Build-All workflow from push-triggered (except main) to manual dispatch only
- Change Check-All workflow from all-branch push triggers to manual dispatch only
- Update doc-site build to trigger on `main` branch pushes and PRs instead of all branches
- Add manual dispatch option to Release workflow while keeping main branch push trigger
- Keep pull request trigger unchanged
=> Update GitHub Actions: Refactor GitHub workflow triggers

build.sbt
- Upgrade `hedgehog` from `0.9.0` to `0.10.1`
- Upgrade `hedgehog-extra` from `0.8.0` to `0.11.0`
=> Close #549: Upgrade `hedgehog` and `hedgehog-extra`

changelogs/0.46.0.md
* [`extras-render`] Add a new implementation of `Render` for Scala 3 using Scala 3 syntax (#543)
* Get rid of `implicit` syntax
* Use `using` and `summon`.
* Use type-class syntax.
* Use `extension` method syntax.
* Use `opaque type`.
* [`extras-render`] Provide an optional instance of `cats.Contravariant[Render]` (#545)
* The instance of `cats.Contravariant[Render]` is available only if the `cats` library is included in the project. Without it, attempting to use or access the instance of the `cats.Contravariant[Render]` type class causes a "**compile-time**" error.
* Although `Render` has a `contramap` extension method, it’s still a good idea to provide an instance of `cats.Contravariant`. Since I don’t want `extras-render` to depend on Cats by default, I want to make it optional using …
=> extras v0.46.0

build.sbt, modules/extras-render/shared/src/main/scala-3/extras/render/Render.scala, modules/extras-render/shared/src/main/scala-3/extras/render/syntax.scala, modules/extras-render/shared/src/test/scala-2/extras/render/ScalaVersionSpecificSyntaxSpec.scala, modules/extras-render/shared/src/test/scala-3/extras/render/ScalaVersionSpecificSyntaxSpec.scala, modules/extras-render/shared/src/test/scala/extras/render/syntaxSpec.scala
Fix #554: [`extras-render`] `.render` `extension` method doesn't work well when there's a method with the same name exists in the context in Scala 3
- Add `ScalaVersionSpecificSyntaxSpec` for Scala 3: to test `render` functionality with Scala 3 features (`opaque type`s, `union type`s, `given` instances)
* Opaque types (`Name`, `MyUnionType`, `Something`)
* Union types (`CaseA` | `CaseB` | `CaseC.type`)
* Given instances instead of implicit definitions
* Extension methods for opaque type operations
- Integrate version-specific tests into existing `syntaxSpec`
- Test property-based scenarios for custom types with render functionality
=> Fix #554: [`extras-render`] `.render` `extension` method doesn't work well when there's a method with the same name exists in the context in Scala 3

changelogs/0.47.0.md
* [`extras-testing-tools`] Add `Scala.js` support (#560)
***
* [`extras-testing-tools`] Add compile-time error check for Scala 2 (#562)
```scala
CompileTimeError.from(
"some Scala code causing a compile-time error"
)
// String = "compile-time error message"
```
=> extras v0.47.0

changelogs/0.48.0.md
=> extras v0.48.0

changelogs/0.49.0.md
* [extras-testing-tools] Support Scala Native (#572)
* `StubTools` is not included because `Thread.currentThread.getStackTrace.toList` returns an empty `List`.
=> extras v0.49.0
